# Generated by Django 2.2.5 on 2019-09-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/static/images/404/404.png', upload_to=None),
        ),
        migrations.AddField(
            model_name='product',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
