# Generated by Django 2.2.5 on 2019-09-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/media/404.png', upload_to=None),
        ),
    ]
